export const TOGGLE_FILTER= 'TOGGLE_FILTER';
export const SEARCH_REQUESTOR= 'SEARCH_FILTER';
export const CLEAR_SEARCH="CLEAR_SEARCH";
export const ADD_REQUESTORS="ADD_REQUESTORS";
export const REMOVE_REQUESTORS="REMOVE_REQUESTORS";
